# Generated by Django 2.1.7 on 2021-05-04 03:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210502_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
