# Generated by Django 2.1.7 on 2021-05-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210504_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='nums',
            field=models.IntegerField(default=0, verbose_name='数量'),
            preserve_default=False,
        ),
    ]
