# Generated by Django 2.1.7 on 2021-05-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_nums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='nums',
        ),
    ]
