# Generated by Django 2.1.7 on 2021-05-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210504_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='是否可以编辑'),
        ),
    ]
